branchName: '${issue.number}-${issue.title[0,64]}'
autoCloseIssue: true
branches:
  - label: enhancement
    prefix: feature/
  - label: bug
    prefix: bugfix/
openDraftPR: true
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueProjectsToPR: true
copyIssueMilestoneToPR: true
prSkipCI: true
conventionalPrTitles: true
gitSafeReplacementChar: '-'
