branchName: "${issue.number}-${issue.title[0,64]}"
autoCloseIssue: true
branches:
  - label: enhancement
    prefix: feat/
  - label: bug
    prefix: fix/
  - label: chore
    prefix: chore/
  - label: docs
    prefix: docs/
  - label: style
    prefix: style/
  - label: refactor
    prefix: refactor/
  - label: test
    prefix: test/
openDraftPR: true
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueProjectsToPR: true
copyIssueMilestoneToPR: true
prSkipCI: true
conventionalPrTitles: true
gitSafeReplacementChar: "-"
