import { ElectronIndicator } from "@/components/generic/ElectronIndicator";
import { TailwindIndicator } from "@/components/generic/TailwindIndicator";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Geist, Geist_Mono } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Suspense } from "react";
import { Toaster } from "sonner";
import "./globals.css";

const geistSans = Geist({
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {
        process.env.NODE_ENV === "development" && (
          <head>
            <script src="https://unpkg.com/react-scan/dist/auto.global.js" async />
          </head>
        )
      }
      <body
        className={`${geistSans.className} ${geistMono.className} antialiased`}
      >
        <ThemeProvider
        >
          <TailwindIndicator />
          <ElectronIndicator />
          <NuqsAdapter>
            <Suspense fallback={<div>Loading...</div>}>
              {children}
            </Suspense>
          </NuqsAdapter>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
