import { createClient } from '@rspc/client';
import { createReactQueryHooks } from '@rspc/react';
import { QueryClient } from '@tanstack/react-query';

import { TauriTransport } from '@rspc/tauri';
import type { Procedures } from './bindings'; // These are generated by rspc in Rust for you.

const client = createClient<Procedures>({
	transport: new TauriTransport(),
});

const queryClient = new QueryClient();
const rspc = createReactQueryHooks<Procedures>();
const useRspcQuery = rspc.useQuery;
const useRspcMutation = rspc.useMutation;

export { client, queryClient, rspc, useRspcMutation, useRspcQuery };
